---
version: '3'

services:
  redis:
    image: redis:alpine3.18
    volumes:
      - redis_data:/data
    restart: always
    expose:
      - 6379
  webapp:
    build: ./
    ports:
      - 8000:5000
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
volumes:
  redis_data: